# ============================================================
# Global Solution 2026/1 - DevOps Tools & Cloud Computing
# App .NET (PM_API) + Banco PostgreSQL
# Representante da equipe: RM561857
# ============================================================

services:

  # ---------- Container do Banco de Dados ----------
  db:
    image: postgres:16
    container_name: db-RM561857
    environment:
      POSTGRES_DB: pmdb
      POSTGRES_USER: pmuser
      POSTGRES_PASSWORD: pmpass123
    ports:
      - "5432:5432"
    volumes:
      - pmdata:/var/lib/postgresql/data
    networks:
      - pmnet
    restart: unless-stopped

  # ---------- Container da Aplicacao (.NET) ----------
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-RM561857          # nome do container contem o RM (exigido)
    environment:
      ConnectionStrings__DefaultConnection: "Host=db-RM561857;Port=5432;Database=pmdb;Username=pmuser;Password=pmpass123"
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - pmnet
    restart: unless-stopped

volumes:
  pmdata:

networks:
  pmnet: